### ISSUE TITLE
[bug] Can't select text for exporting when using Beaker

### ISSUE THREAD

**Issue by composition4** [hundredrabbits/Dotgrid#11]
## Priority
Critical

## Steps to Reproduce
* open site in Beaker
* make a thing
* press (e) to export the thing
* try in vain to select text for export with copy-paste
* lay down & cry 😭 , fall asleep on wet pillow

## Expected
Selectable text to copypaste to file

## Actual
Can see text but cannot select it for copypaste, must instead visually type in every detail into other file 😞 

## Versions
Beaker 0.7.7
Dotgrid current (no version # supplied)
xubuntu linux zesty

**NOTE**: Should this be labeled specifically for Beaker Browser in some manner?

**Comment by neauoire** [comment]
Fixed :)
