### ISSUE TITLE
Problem with Keyboard shortcuts on German Layout on Linux and Windows

### ISSUE THREAD

**Issue by earthnuker** [hundredrabbits/Dotgrid#18]
The keyboard shortcuts for increasing/decreasing the line width don't seem to work properly on Linux when using the German Keyboard Layout (`X11 Layout: de` according to `localectl status`)

"decrease line width" appears to be mapped to the `ß` key and I haven't found the "increase line width"

A similar Problem occurs on Windows 7, except that here both increase and decrease work but are mapped to `` ` `` and `ß`.

**Comment by neauoire** [comment]
I will add an icon, do you have the `[` and `]` keys on your keyboard?

**Comment by earthnuker** [comment]
Thanks,
an yes, [ and ] are  AltGr + 8 and AltrGr + 9 on my Keyboard layout.

**Comment by neauoire** [comment]
A bit awkward then, I'll use +/-

**Comment by npisanti** [comment]
I have the same problem on Debian ( locale set to `X11 Layout: it`) with the dotgrid-linux-64 version, it works fine by using the online version. 
The icon button just increases the size, so no turning back.

PS: i found that the fine controls are mapped to ? and ^ and the +5 controls are mapped to ' and ì 
(i'm leaving this comment here also for reference, as i can deal with it as long as i know there are some keys for that)

**Comment by movAX13h** [comment]
This problem still exists on windows with german keyboard. `[` and `]` are ot working as expected. Also z and y positions on keyboard are swapped.

**Comment by neauoire** [comment]
I cannot test this, my suggestion is to make a fork until I get access to a keyboard with which I can test.
