### ISSUE TITLE
[Feature Request] Run dotgrid at 2x/3x scale

### ISSUE THREAD

**Issue by level0dev** [hundredrabbits/Dotgrid#21]
I have tried using dotgrid on my laptop that not only has a small-ish screen, but it also runs at high resolution, which ends up with dotgrid window being smaller than a quarter of my screen. This is far from perfect, and makes the grid really hard to see.

It would be really helpful if the app could be run at a larger scale (command option to run the .exe with parameter -2x would be plenty)

**Comment by neauoire** [comment]
Can do!

**Comment by neauoire** [comment]
Sorry for the delay :) I had to rebuild some of the core parts to allow this to work properly.
