### ISSUE TITLE
Show preview of controls

### ISSUE THREAD

**Issue by AnastasiaDunbar** [hundredrabbits/Dotgrid#24]
Like this: 
![preview](https://user-images.githubusercontent.com/11806048/33521546-ae45a540-d80f-11e7-94f5-8b8d7de0a8ca.gif)

**Comment by neauoire** [comment]
Hi Anastasia, this is an amazing idea!!
You look like you have it working, would you like to make pull request so I can merge it with the main build? If you don't feel confident about this, I can rebuilt it too, no problem.

**Comment by AnastasiaDunbar** [comment]
I didn't change the code but used Photoshop.

**Comment by neauoire** [comment]
You fooled me.

**Comment by neauoire** [comment]
Alright I will implement this : )

**Comment by neauoire** [comment]
Enjoy!
https://twitter.com/hundredrabbits/status/937154224625827840
