### ISSUE TITLE
close single path

### ISSUE THREAD

**Issue by denvist** [hundredrabbits/Dotgrid#26]
Hi! Is it possible to close single path? May be close paths by layer?

![screen shot 2018-03-04 at 13 17 26](https://user-images.githubusercontent.com/7146527/36944485-6f227578-1fae-11e8-90f7-f99cfb00479a.png)

**Comment by neauoire** [comment]
That's a good idea, I can give each layer their own settings! 
Would that work for you?

**Comment by denvist** [comment]
@neauoire, yes!

**Comment by neauoire** [comment]
On it :)

**Comment by neauoire** [comment]
Released :)

**Comment by neauoire** [comment]
Fixed 👍
