### ISSUE TITLE
Closed path's rendered as transparent

### ISSUE THREAD

**Issue by denvist** [hundredrabbits/Dotgrid#27]
Subject. Svg - ok, png - no.

![screen shot 2018-03-04 at 20 09 10](https://user-images.githubusercontent.com/7146527/36948193-0786263c-1fe8-11e8-8fdc-26f5b1b85861.png)

**Comment by neauoire** [comment]
I'll fix this now.
thanks for the bug report :)

**Comment by neauoire** [comment]
<img width="800" alt="screen shot 2018-03-05 at 9 00 22 am" src="https://user-images.githubusercontent.com/1455726/36949941-a90bc942-2053-11e8-98e1-26067f443d3a.png">

I don't seem to be having this issue.
Can you make sure you have the latest version? And that the console gives you no error `cmd+.`

**Comment by denvist** [comment]
Version 45. PNG image a empty

![screen shot 2018-03-05 at 01 40 09](https://user-images.githubusercontent.com/7146527/36951546-304e5264-2016-11e8-9092-c0597a8ba1b5.png)

**Node version:** 8.9.4

![screen shot 2018-03-05 at 02 01 41](https://user-images.githubusercontent.com/7146527/36951830-38267554-2019-11e8-9171-7584ab302dd3.png)

**Comment by denvist** [comment]
Version 46 - same behavior :(

**Comment by neauoire** [comment]
I will try again
