### ISSUE TITLE
Unable to open saved dot's files

### ISSUE THREAD

**Issue by denvist** [hundredrabbits/Dotgrid#28]
Hi again! i'm unable to open previously created files after upgrade dotgrid to version 49. There is nothing errors or warnings in Inpect. Did you make some break changes with dot's format? Should i recreate existing files?

**Comment by neauoire** [comment]
I have, you can have a look at the file changes, I now wrap the old dotgrid file in an object. you can replicated this change on your old files if you want to bring them to the new version.

**Comment by denvist** [comment]
Oh no.. "Incompatible version" tool.js:63 :(

**Comment by neauoire** [comment]
just put your old dot file content in 

```
{
  "layers": OLD_FORMAT_GOES_HERE,
  "styles": [
    {
      "thickness": 5,
      "strokeLinecap": "round",
      "strokeLinejoin": "round",
      "color": "#fff",
      "fill": "none"
    },
    {
      "thickness": 5,
      "strokeLinecap": "round",
      "strokeLinejoin": "round",
      "color": "#777",
      "fill": "#777"
    },
    {
      "thickness": 5,
      "strokeLinecap": "round",
      "strokeLinejoin": "round",
      "color": "#444",
      "fill": "none"
    }
  ]
}
```
