### ISSUE TITLE
Check for updates/update binary in app

### ISSUE THREAD

**Issue by rickycodes** [hundredrabbits/Dotgrid#29]
re: https://twitter.com/rickycodes/status/974385695501496322

**Comment by rickycodes** [comment]
Again, this is a feature I could spike if you're interested

**Comment by neauoire** [comment]
I would love this! and if you could have a look at the /lib folder. These files are shared among [Left](http://github.com/hundredrabbits/left) and [Marabu](http://github.com/hundredrabbits/marabu). If you can possibly make it a single standalone file, I will bring it across all the ecosystem! 👍

**Comment by rickycodes** [comment]
I'll take a look at how Hyper, Brave and others are doing this and see how easy it'll be to bring over

I'll def keep it isolated (as you mentioned) so it'll be easy to have an additional `menuItem` you can drop into "all the things"

(there may even be a module that exists to do this already)

**Comment by rickycodes** [comment]
@neauoire so, this is a bit more involved than I previously thought!...

There is an `autoUpdater` in Electron: https://github.com/electron/electron/blob/master/docs/api/auto-updater.md

and here's a <a href='https://github.com/electron/electron/blob/master/docs/tutorial/updates.md'>detailed guide</a>

It looks like there are a couple ways to go about this, but the TL;DR is that we'd have to leverage GitHub releases.

You can **a)** use an update server (Hyper uses <a href='https://github.com/zeit/hazel'>Hazel</a>, for example)

Or **b)** use <a href='https://github.com/electron-userland/electron-builder'>`electron-builder`</a> to package your app, which has <a href='https://www.electron.build/auto-update'>`electron-updater`</a> which has its own `autoUpdater` which doesn't require a dedicated update server (I'd recommend this, assuming you're cool with changing how you package the app, or maybe you're already using this?)

Let me know and I'll tinker around with whichever option makes the most sense

**Comment by neauoire** [comment]
With the [Live version](https://hundredrabbits.github.io/Dotgrid/), I think this is less necessary.
