### ISSUE TITLE
Curves not mirroring properly

### ISSUE THREAD

**Issue by jaybaptista** [hundredrabbits/Dotgrid#34]
When defining a curve, it doesn't mirror horizontally as expected, instead it mirrors the points but the curve isn't mirrored exactly.

![image](https://user-images.githubusercontent.com/6158907/39906814-bd9229d6-5480-11e8-8e30-cb16861b16db.png)

**Comment by neauoire** [comment]
I've been trying to solve this actually, it's a tricky one. If you have any idea how to mirror SVG paths(not using) I could do with a bit of help.

**Comment by neauoire** [comment]
`/scripts/generator.js`

**Comment by jaybaptista** [comment]
I'm currently studying for exams this week so I can't really look into it
but maybe try to make a new layer for mirrored segments, then for the new
layer/context just scale it in the inverse direction (
https://www.w3.org/TR/2dcontext/#dom-context-2d-scale) somewhere like: "
layer.setScale(-1, 1) ", which should just mirror the segment and I
understand that the points are already offset in generator.js so maybe it
would work?

**Comment by neauoire** [comment]
That's how it was before and isn't quite good enough.
I'll figure it out, I think I have found something that works~
Will do some further testing.

**Comment by neauoire** [comment]
<img width="572" alt="screen shot 2018-05-12 at 9 32 38 am" src="https://user-images.githubusercontent.com/1455726/39947873-9e38e03c-55c7-11e8-9b97-5c9f8621ee13.png">

<img width="582" alt="screen shot 2018-05-12 at 9 32 30 am" src="https://user-images.githubusercontent.com/1455726/39947882-a5ae3cb8-55c7-11e8-9a56-bddffbc7a5f0.png">

<img width="539" alt="screen shot 2018-05-12 at 9 32 22 am" src="https://user-images.githubusercontent.com/1455726/39947883-a9297e16-55c7-11e8-9d53-8635a0d50bbe.png">
