### ISSUE TITLE
Image size gets greater every time you save

### ISSUE THREAD

**Issue by Kalkhas** [hundredrabbits/Dotgrid#36]
Every time you press the commands to __save/export/render__ a file it gets ~2 times bigger.
If the image is 300x300, it'll be 600x600, then 1200x1200, etc.
The window doesn't grow with it though so you only notice this when the image is saved (or when you try to modify the image size).

There is no need to actually save the file to get this behaviour, only press the keys.

**Comment by neauoire** [comment]
Oh weiiiird, let me investigate.
