### ISSUE TITLE
Weird things happen after I close a path

### ISSUE THREAD

**Issue by nihilocrat** [hundredrabbits/Dotgrid#4]
(Using Windows 10 64 bit, binaries from itch.io)

1. Place control points in a triangle and press D to form an incomplete triangle
2. Press R to close the path
3. Draw a segment someplace else with control points and D
4. Notice that the segment uses one of the points from the triangle as a control point.

Step 4 does not happen if you do steps 1 and 3 without doing 2.

**Comment by neauoire** [comment]
I got this bug too! Thanks for spotting this one, I had this happen once but couldn't replicate.
I will fix :)

**Comment by neauoire** [comment]
Fixed :)
