### ISSUE TITLE
Symmetry and arc_*

### ISSUE THREAD

**Issue by UnwarySage** [hundredrabbits/Dotgrid#42]
Creating a three point arc_c or arc_d, and then enabling symmetry make the mirrored part use the opposite tool. IE, arc_c is mirrored to an arc_d in rotational symmetric mirroring mode. (mirror mode three?)

tested on linux, and web versions, both freshly downloaded as of today.

**Comment by neauoire** [comment]
Good catch!


<img width="397" alt="screen shot 2018-12-15 at 8 05 34 am" src="https://user-images.githubusercontent.com/1455726/50024880-478f6e80-0040-11e9-94d6-f8a8e55a8c3e.png">
