### ISSUE TITLE
Resize window on Windows 8 not possible

### ISSUE THREAD

**Issue by a-gerescher** [hundredrabbits/Dotgrid#45]
It's not possible to resize the window size on Windows 8 any more.
Don't know if its related to german keyboard, or what exactly is going wrong.
Maybe it's better if you are on plattform windows, to readd the window borders again?

Great software by the way :-)

**Comment by n-rafael** [comment]
Seeing the same on windows 10 -- can't seem to find the window-resize handle.

**Comment by neauoire** [comment]
Could you test the latest version and tell me if that's still the case?

**Comment by neauoire** [comment]
I have tested on vm and works for me.

**Comment by a-gerescher** [comment]
Works for me, paid 20 $ on itch. 
May the wind always be at your back.

**Comment by n-rafael** [comment]
Agreed -- Seems good now! Thanks.
