### ISSUE TITLE
can't save a resulting image

### ISSUE THREAD

**Issue by vykhovanets** [hundredrabbits/Dotgrid#51]
Ubuntu 18.10 
I cant save nor in svg nor in png format. the window with directories tree freezes and becomes unresponsive. :( 

when launched as electorn package through `npm start` saw an error `g-io-error-quark, 13`

saving only works in browser here https://hundredrabbits.github.io/Dotgrid/ but, when I save 'mirrored' image - canvas resizes faster than the actual saving (canvas resize prodused by Chrome, when it show the downloading process at the bottom)

**Comment by vykhovanets** [comment]
also I saw when I use shortcut `ctrl+e` - everething works. 

+ I am using version 128

**Comment by neauoire** [comment]
Weird, I cannot replicate the error. Let me see if I can find someone else with Ubuntu. 
I have Debian and FreeBSD and they both export alright.
