### ISSUE TITLE
Guide Dots don't override layer

### ISSUE THREAD

**Issue by soyboysky** [hundredrabbits/Dotgrid#52]
With a version from around October, i was able to fill in the 3rd layer completely black, then go to the first layer and the guiding dots would show up in grey over top of the black layer. With the previous 2 versions, this is not possible, and im not sure if it was intentional or not. If this could be toggleable, or put back into the system, i could use it so much more. I used to use this app for all my Macbook's App Icons, using black square backgrounds. Now i cant create them because i cant see what im doing. (i realize i can create the white outline first, but i dislike doing this because it doesnt give me the idea of what it would look like as a final product.)

**Comment by neauoire** [comment]
This is a bit of convoluted issue, so:

1) I draw a black shape in the 3rd layer:

<img width="342" alt="screen shot 2019-03-06 at 9 12 25 am" src="https://user-images.githubusercontent.com/1455726/53846393-0af46300-3ff0-11e9-9aae-32cc5d9988c6.png">

2) I go to the first layer, the 3rd layer's control points are hidden:

<img width="318" alt="screen shot 2019-03-06 at 9 12 32 am" src="https://user-images.githubusercontent.com/1455726/53846417-2a8b8b80-3ff0-11e9-8faa-9ba88d1c81eb.png">

3) Are you saying that you don't see the control points of the layer 1, like so:

<img width="350" alt="screen shot 2019-03-06 at 9 13 46 am" src="https://user-images.githubusercontent.com/1455726/53846426-32e3c680-3ff0-11e9-986c-70342c03098c.png">

**Comment by soyboysky** [comment]
yes, exactly. My main issue is that for all of my designs, i create a black square background on the 3rd layer (filling up the entire space), so I cant see what im doing when i try to make the design on the first layer.

**Comment by neauoire** [comment]
You should still see white dots tho?

<img width="458" alt="Screen Shot 2019-03-28 at 8 43 24 AM" src="https://user-images.githubusercontent.com/1455726/55119534-9798c980-5135-11e9-922b-ef8c156a748a.png">
