### ISSUE TITLE
weird fullscreen bug on macOS 10.13.6

### ISSUE THREAD

**Issue by wakest** [hundredrabbits/Dotgrid#53]
this is fullscreen split with Messages.app
<img width="1680" alt="screen shot 2019-01-14 at 7 17 02 pm" src="https://user-images.githubusercontent.com/7890201/51151693-5df03c00-1831-11e9-81cb-b28ec313f8ed.png">

image looks like this when fullscreen not shared with another app
<img width="395" alt="screen shot 2019-01-14 at 7 21 55 pm" src="https://user-images.githubusercontent.com/7890201/51151782-adcf0300-1831-11e9-9fed-ceefe74b2919.png">

**Comment by neauoire** [comment]
Can you explain to me what the bug is exactly?
It crops the image? Is it just related to the mirror?

**Comment by neauoire** [comment]
Duplicate of #50
