### ISSUE TITLE
UDP control expansion?

### ISSUE THREAD

**Issue by VegaDeftwing** [hundredrabbits/Dotgrid#56]
The UDP control is relatively limited, some potential improvements include control of:
line thickness,
fill,
color,
and mirroring

Speaking of mirroring, UDP controlled input does not mirror like by-hand input.

Finally, it appears that the clear command over UDP does not respect layers but instead clears everything. I haven't yet tested if the same is true for draw or if layers are respected at all, as I'm unsure if this is simply a misunderstanding of the desired behavior.

**Comment by neauoire** [comment]
I've removed UDP for now, maybe revisit this in the future :)
