### ISSUE TITLE
Is the project open to contributions?

### ISSUE THREAD

**Issue by croqaz** [hundredrabbits/Dotgrid#57]
Just like the title sais.
I can contribute with ideas for features and maybe code, some automated tests.
What would be the best way to contribute? I left a few comments in Mastodon about my initial ideas.

* I think more than 3 layers would allow more flexibility
* I don't really understand what is actually selected and how deleting shapes works; Maybe there's some room for improvement? Or maybe it's something not documented?
* .grid format might be more flexible if it was [JSON5](https://json5.org/) - not sure if the project allows extra libraries for that?

**Comment by neauoire** [comment]
It's possible that the thing missing is extra docs and tutorials. That would be an excellent way to contribute. If you think you can improve the UI/UX, give it a shot.

**Comment by croqaz** [comment]
Hey, sorry for replying to slowly.

So I have a few minor suggestions and fixes regarding the documentation.

From the link to the homepage: https://hundredrabbits.itch.io/dotgrid there's another link to the guide of Dotgrid: https://100r.co/blog.html#dotgrid <- this is broken.
So you have to manually search and navigate to the correct URL: https://100r.co/pages/dotgrid.html
My suggestion is to move the guide to this repository's README file, where it's easier to maintain and version in Git.
Or at least keep the real guide here and just mirror it to the 100r.co ?

The only thing that is missing from the Dotgrid guide is "right click on a path will delete the path". That's a hidden feature and it should be explained.

Feel free to do as you please, as I'm sure you'll do anyway :)

**Comment by croqaz** [comment]
I will start working on allowing more than 3 layers in Dotgrid, but I'll be slow, because I work late at night and my productivity is really bad.
I also think viewing some "debug" values like: the numeric value of the thickness, the linecap value, the linejoin value; are useful especially when you transition to a new layer.
I'll add all the details when I start working on them, to get feedback in case I'm going in a wrong direction.

**Comment by neauoire** [comment]
The dotgrid guide sources is [here](https://github.com/hundredrabbits/100r.co/blob/master/build/database/tools.ndtl#L74), thanks for the broken link report on the itch page, I'll fix that.
