### ISSUE TITLE
Undo is broken in web version for non OSX platforms.

### ISSUE THREAD

**Issue by neauoire** [hundredrabbits/Dotgrid#66]

**Comment by alizehctl** [comment]
I think export might also be broken

![image](https://user-images.githubusercontent.com/31581044/70558957-a4682b00-1ba7-11ea-977a-8a8fcf8e6292.png)

**Comment by neauoire** [comment]
Ah yes, the change I did to history broke the export and support, just fixed it :)
Let me know if that works for you now.

**Comment by alizehctl** [comment]
@neauoire 

It works! At least with the keyboard shortcut. Clicking on the save icon at the bottom generates the same TypeError

![image](https://user-images.githubusercontent.com/31581044/70631112-7e499600-1c4e-11ea-8d85-80e2983b50e9.png)

**Comment by neauoire** [comment]
Ah! Gotcha :) Fixed in lasted commit!
Thanks
