### ISSUE TITLE
Suggestion: Implement the ability to select multiple dots.

### ISSUE THREAD

**Issue by DetonDev** [hundredrabbits/Dotgrid#75]
Today I was playing around with Dotgrid and trying to make a spritesheet of minimalist icons. However, I eventually needed a bit more room and needed to move around the sprites to get that room. But the only way I can see from the Dotgrid documentation for moving those sprites is to drag each dot up, individually, until they are all where I want 'em to be.

So I think implementing a way to select multiple dots and manipulate them all at once would be beneficial to users who have lots of dots onscreen and would have to go through the tedious process of moving them all individually if the need arises.

**Comment by neauoire** [comment]
I've updated the README and made clearer how to move entire segments at once :)

- Hold Shift to drag a segment.
- Hold Alt to drag all segments.
- Right-click to delete a vertex.

video: https://twitter.com/hundredrabbits/status/1252739458421518337

**Comment by DetonDev** [comment]
Ah okay. Thanks!
