### ISSUE TITLE
Feature Request: More than three layers

### ISSUE THREAD

**Issue by finngreiter** [hundredrabbits/Dotgrid#78]
Hopefully, this isn't too much trouble, but I was wondering if there are only three layers for a reason, or if more could be added.

I really enjoy using this tool, thanks.

**Comment by rekkabell** [comment]
Glad you like it :). 

Dotgrid only has 3 layers in the spirit of keeping things simple. We have no plans to add more, sorry.

If it's a feature that is really important to you, you can fork this repository to add this feature. We can help you with this if you want.
