### ISSUE TITLE
How to build this app from source?

### ISSUE THREAD

**Issue by Leedehai** [hundredrabbits/Dotgrid#82]
Hi - could you give instructions in the Readme on how to build the app from source code? :slightly_smiling_face:

**Comment by neauoire** [comment]
It's not an app, it's just a web page. Are you looking for the C(SDL) version of dotgrid?

**Comment by Leedehai** [comment]
Thanks @neauoire! Yeah I found this app from [Electron's app page](https://www.electronjs.org/apps/dotgrid) and didn't realize there are multiple versions of Dotgrid.
