### ISSUE TITLE
Remove with right click

### ISSUE THREAD

**Issue by xavierfoucrier** [hundredrabbits/Dotgrid#9]
Add the ability to **remove a specific point** from the drawing area by doing a right click on the point.

**Comment by neauoire** [comment]
Fixed https://github.com/hundredrabbits/Dotgrid/commit/093c320eab3306ad6cf8e17dfe89416f205367fe

**Comment by neauoire** [comment]
Fixed https://github.com/hundredrabbits/Dotgrid/commit/093c320eab3306ad6cf8e17dfe89416f205367fe
